mysql:
  host: "localhost"
  port: "3308"
  user: "root"
  password: "root"
  dbname: "qa"

mongo:
  host: "110.41.2.77"
  port: 27017
  user: "admin"
  pwd: "admin"

server:
  host: "localhost"
  port: ":8088"

remote:
  remote_dir: "/Users/u3d/jenkins/workspaces/webglhost-auto-android/app"
  adb_path: "/usr/local/platform-tools/"

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0

feishu:
  form_api : "https://open.feishu.cn/open-apis/sheets/v2/spreadsheets"
  user_token_api : "https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal"
  sheetToken : "QOmLsuG1xhnjdgt55RwcTu4infe"
  tap_sheetId : "YEZq2R"
  app_id : "cli_a78cf6cbd299100c"
  app_secret : "MgyNcjG6s8ztJ2er7JHKCbemw6YQgyqS"
  range: "A1:U500"