mysql:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"
  dbname: "qa"

mongo:
  host: "127.0.0.1"
  port: 27017
  user: "admin"
  password: "secret"

server:
  host: "localhost"
  port: ":8088"

remote:
  remote_dir: "/Users/u3d/jenkins/workspaces/webglhost-auto-android/app"
  adb_path: "/usr/local/platform-tools/"

redis:
  host: "10.86.97.133"
  port: 6379
  db: 0