mysql:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"
  dbname: "qa"

server:
  host: "localhost"
  port: ":8088"

remote:
  remote_dir: "/Users/u3d/jenkins/workspaces/webglhost-auto-android/app"
  adb_path: "/usr/local/platform-tools/"