/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/device/add_phone': RouteRecordInfo<'/device/add_phone', '/device/add_phone', Record<never, never>, Record<never, never>>,
    '/device/device_manage': RouteRecordInfo<'/device/device_manage', '/device/device_manage', Record<never, never>, Record<never, never>>,
    '/device/upload': RouteRecordInfo<'/device/upload', '/device/upload', Record<never, never>, Record<never, never>>,
    '/game/database': RouteRecordInfo<'/game/database', '/game/database', Record<never, never>, Record<never, never>>,
    '/game/game_manage': RouteRecordInfo<'/game/game_manage', '/game/game_manage', Record<never, never>, Record<never, never>>,
    '/game/quick_game': RouteRecordInfo<'/game/quick_game', '/game/quick_game', Record<never, never>, Record<never, never>>,
    '/game/wxmini_game': RouteRecordInfo<'/game/wxmini_game', '/game/wxmini_game', Record<never, never>, Record<never, never>>,
    '/home/home': RouteRecordInfo<'/home/home', '/home/home', Record<never, never>, Record<never, never>>,
    '/phone/phone_manage': RouteRecordInfo<'/phone/phone_manage', '/phone/phone_manage', Record<never, never>, Record<never, never>>,
    '/watcher/watcher_manage': RouteRecordInfo<'/watcher/watcher_manage', '/watcher/watcher_manage', Record<never, never>, Record<never, never>>,
  }
}
